/* Corrida do Saber - Configuracoes e dados estaticos */

(() => {
  const CONFIG_RADAR_REAL = {
    inset: 12,
    altitude: 340,
    folgaMapa: 18,
  };

  const LIMITES_DE_JOGO = {
    EXIBIR_HUD_SECUNDARIA: false,
    MAX_POLICIAS_ATIVAS: 4,
    TEMPO_RESPAWN_CAPOTADO: 5,
    COOLDOWN_RESPAWN_MANUAL: 1.2,
    TEMPO_INATIVIDADE_HELICOPTERO: 30,
    INTERVALO_ATAQUE_HELICOPTERO: 1.2,
    MAX_PROJETEIS_HELICOPTERO: 4,
  };

  const PALETA_CENARIO = {
    montanhas: [0x95a183, 0x879374, 0xa8b193, 0x788567, 0xb8c1a6],
    troncos: [0x8a5a30, 0x764928, 0x9a6a3c],
    arvores: [0x4d9943, 0x5ca84e, 0x3f8836, 0x72b75f, 0x5b9a48],
    pedras: [0x95a0a8, 0x818c95, 0xb2b9bf, 0x727b84, 0xa0a7ae],
    rampas: [0xf0b34a, 0xe7815a, 0x64a5d9, 0x6dbd74, 0xc96b6b],
    arbustos: [0x4b913f, 0x5da84b, 0x3d7d34, 0x74ba60],
    cones: [0xf0a35a, 0xe9bf63, 0xe07a5f],
    caixas: [0xc88c4c, 0xb87d43, 0xd5a36a, 0x9e6a39],
  };

  const CONFIG_NAVEGACAO_POLICIA = {
    passo: 26,
    margemMapa: 24,
    folgaNodo: 6,
    folgaSegmento: 6,
    distanciaLigacao: 38,
    conexoesTemporarias: 6,
    intervaloRecalculo: 0.55,
    distanciaChegada: 8,
    desvioRecalculo: 12,
    maxNosExpandidos: 260,
  };

  const CONFIG_CONFORTO_MOVIMENTO = {
    fovBase: 69,
    fovExtra: 1.2,
    suavizacaoCamera: 3.4,
    suavizacaoAlvo: 3.1,
    overlayInicio: 0.9,
    overlayIntensidade: 0.08,
    rotacaoMenu: 0.14,
    fatorSaltoRampa: 0.78,
    fatorEmpurraoColisao: 0.72,
    fatorImpactoTela: 0.45,
  };

  const CONFIG_TATICA_POLICIAL = {
    raioLeituraSilaba: 48,
    raioRespostaPolicial: 72,
    distanciaBloqueioMin: 6,
    distanciaBloqueioMax: 12,
    distanciaColisao: 16,
    alinhamentoMinimo: 0.28,
  };

  const STORAGE_KEYS = {
    CHAVE_PONTOS: "corridaDoSaber:pontos",
    CHAVE_CARRO: "corridaDoSaber:carroSelecionado",
    CHAVE_CARROS_DESBLOQUEADOS: "corridaDoSaber:carrosDesbloqueados",
  };

  const ESTADO_INICIAL = {
    grupoFaseAtual: "facil",
    carroSelecionado: "classico",
    tempoCapturaPolicia: 1.8,
    carrosDesbloqueados: ["classico"],
  };

  const garagemCarros = {
    classico: {
      nome: "Clássico",
      visual: "classico",
      titulo: "Equilíbrio",
      custo: 0,
      descricao: "Confiável, fácil de controlar e ótimo para começar.",
      carroceria: 0xd64045,
      vidro: 0x1f2a44,
      detalhe: 0xffd166,
      asa: 0x90e0ef,
      faixa: 0xffd166,
      teto: 0x00a0ff,
      velocidadeMaxima: 42,
      aceleracao: 52000,
      freio: 30000,
      curva: 1.9,
      tracao: 0.86,
      impulsoRampa: 38,
      saltoRampa: 17.5,
      cameraAltura: 8,
      cameraDistancia: 20,
      nivelVelocidade: 2,
      nivelAceleracao: 2,
      nivelControle: 3,
    },
    esportivo: {
      nome: "Desportivo",
      visual: "esportivo",
      titulo: "Curvas Perfeitas",
      custo: 100,
      descricao: "Gruda nas curvas, mas perde fôlego nas retas longas.",
      carroceria: 0x1976d2,
      vidro: 0x102a43,
      detalhe: 0xffffff,
      asa: 0xffffff,
      faixa: 0xffffff,
      teto: 0xffffff,
      velocidadeMaxima: 44,
      aceleracao: 61000,
      freio: 40000,
      curva: 2.7,
      tracao: 0.96,
      impulsoRampa: 39,
      saltoRampa: 17.8,
      cameraAltura: 8,
      cameraDistancia: 19,
      nivelVelocidade: 2,
      nivelAceleracao: 3,
      nivelControle: 5,
    },
    pickup: {
      nome: "Monstro",
      visual: "pickup",
      titulo: "Peso Pesado",
      custo: 180,
      descricao:
        "Dispara forte, mas gira pouco e escorrega nas manobras.",
      carroceria: 0x2e7d32,
      vidro: 0x1b5e20,
      detalhe: 0x111111,
      asa: 0x4caf50,
      faixa: 0x111111,
      teto: 0x111111,
      velocidadeMaxima: 55,
      aceleracao: 82000,
      freio: 34000,
      curva: 1.4,
      tracao: 0.8,
      impulsoRampa: 40,
      saltoRampa: 17.6,
      cameraAltura: 9.5,
      cameraDistancia: 22,
      nivelVelocidade: 4,
      nivelAceleracao: 4,
      nivelControle: 1,
    },
    f1: {
      nome: "Fórmula Z",
      visual: "f1",
      titulo: "Velocidade Pura",
      custo: 250,
      descricao:
        "Nasceu para voar em linha reta e derrapar em toda curva.",
      carroceria: 0xd50000,
      vidro: 0x000000,
      detalhe: 0xffeb3b,
      asa: 0xff0000,
      faixa: 0xffeb3b,
      teto: 0xffeb3b,
      velocidadeMaxima: 78,
      aceleracao: 92000,
      freio: 42000,
      curva: 1.6,
      tracao: 0.75,
      impulsoRampa: 49,
      saltoRampa: 20.4,
      cameraAltura: 7.2,
      cameraDistancia: 17.5,
      nivelVelocidade: 5,
      nivelAceleracao: 4,
      nivelControle: 2,
    },
    hipercarro: {
      nome: "Hipercarro",
      visual: "hiper",
      titulo: "Futurista",
      custo: 400,
      descricao:
        "Explode na arrancada, mas estabiliza numa velocidade média.",
      carroceria: 0x6a0dad,
      vidro: 0x0b132b,
      detalhe: 0x90e0ef,
      asa: 0x90e0ef,
      faixa: 0x90e0ef,
      teto: 0x90e0ef,
      velocidadeMaxima: 58,
      aceleracao: 105000,
      freio: 50000,
      curva: 2.15,
      tracao: 0.88,
      impulsoRampa: 47,
      saltoRampa: 19.6,
      cameraAltura: 7.2,
      cameraDistancia: 17.5,
      nivelVelocidade: 3,
      nivelAceleracao: 5,
      nivelControle: 3,
    },
    "moto-urbana": {
      nome: "Moto Azul",
      visual: "moto-urbana",
      titulo: "Velocidade Normal",
      custo: 480,
      descricao:
        "Moto equilibrada, fácil de controlar e boa para qualquer fase.",
      carroceria: 0x2f80ed,
      vidro: 0x0f2d52,
      detalhe: 0xbfe3ff,
      asa: 0xbfe3ff,
      faixa: 0xe6f4ff,
      teto: 0xe6f4ff,
      velocidadeMaxima: 50,
      aceleracao: 60000,
      freio: 41000,
      curva: 2.95,
      tracao: 0.95,
      impulsoRampa: 40,
      saltoRampa: 17.8,
      cameraAltura: 7.4,
      cameraDistancia: 18.2,
      nivelVelocidade: 3,
      nivelAceleracao: 3,
      nivelControle: 5,
    },
    rally: {
      nome: "Rally X",
      visual: "rally",
      titulo: "Todo Terreno",
      custo: 650,
      descricao:
        "Doma terra, rampas e impacto melhor do que qualquer outro.",
      carroceria: 0xf77f00,
      vidro: 0x1f2a44,
      detalhe: 0xffffff,
      asa: 0x90e0ef,
      faixa: 0xffffff,
      teto: 0xffffff,
      velocidadeMaxima: 54,
      aceleracao: 66000,
      freio: 45000,
      curva: 2.3,
      tracao: 1.0,
      impulsoRampa: 52,
      saltoRampa: 20.2,
      cameraAltura: 8.4,
      cameraDistancia: 19.8,
      nivelVelocidade: 3,
      nivelAceleracao: 3,
      nivelControle: 4,
    },
    turbovan: {
      nome: "Turbo Van",
      visual: "turbovan",
      titulo: "Potência Escondida",
      custo: 780,
      descricao:
        "Grande, estável e surpreendentemente veloz em qualquer fase.",
      carroceria: 0x457b9d,
      vidro: 0x0b132b,
      detalhe: 0xe9c46a,
      asa: 0xe9c46a,
      faixa: 0xe9c46a,
      teto: 0xe9c46a,
      velocidadeMaxima: 62,
      aceleracao: 74000,
      freio: 48000,
      curva: 2.18,
      tracao: 0.94,
      impulsoRampa: 45,
      saltoRampa: 19.0,
      cameraAltura: 8.8,
      cameraDistancia: 20.5,
      nivelVelocidade: 4,
      nivelAceleracao: 3,
      nivelControle: 4,
    },
    "moto-trilha": {
      nome: "Moto Racing",
      visual: "moto-trilha",
      titulo: "Corrida Rápida",
      custo: 980,
      descricao:
        "Moto de corrida vermelha, mais rápida e feita para acelerar forte.",
      carroceria: 0xe53935,
      vidro: 0x2a0c0b,
      detalhe: 0xfff176,
      asa: 0xffc107,
      faixa: 0xfff176,
      teto: 0xfff176,
      velocidadeMaxima: 74,
      aceleracao: 98000,
      freio: 50000,
      curva: 2.7,
      tracao: 0.9,
      impulsoRampa: 52,
      saltoRampa: 20.8,
      cameraAltura: 7.2,
      cameraDistancia: 17.8,
      nivelVelocidade: 5,
      nivelAceleracao: 5,
      nivelControle: 3,
    },
    phantom: {
      nome: "Phantom",
      visual: "hiper",
      titulo: "Silencioso",
      custo: 1100,
      descricao:
        "O mais completo da garagem: rápido, firme e difícil de errar.",
      carroceria: 0x2b2d42,
      vidro: 0x0b132b,
      detalhe: 0x8d99ae,
      asa: 0x8d99ae,
      faixa: 0x8d99ae,
      teto: 0x8d99ae,
      velocidadeMaxima: 76,
      aceleracao: 90000,
      freio: 58000,
      curva: 2.6,
      tracao: 0.93,
      impulsoRampa: 52,
      saltoRampa: 22,
      cameraAltura: 7.0,
      cameraDistancia: 17.4,
      nivelVelocidade: 5,
      nivelAceleracao: 4,
      nivelControle: 5,
    },
  };

  window.CorridaDoSaberConfig = {
    CONFIG_RADAR_REAL,
    LIMITES_DE_JOGO,
    PALETA_CENARIO,
    CONFIG_NAVEGACAO_POLICIA,
    CONFIG_CONFORTO_MOVIMENTO,
    CONFIG_TATICA_POLICIAL,
    STORAGE_KEYS,
    ESTADO_INICIAL,
    garagemCarros,
  };
})();